#
# Blog Settings
#
author: Philipp Mager
description: Get Sharp, Be Sharp, Stay Sharp
url: http://phmager.github.io
title: Get Sharp, Be Sharp, Stay Sharp
subtitle: Everything you need to know about C#
gravatar_url: /images/me.png
subscribe_rss: 

# Github repositories
github_user: phmager
github_repo_url: https://github.com/phmager/phmager.github.io/

# Twitter
twitter_user: PhilippMager
twitter_tweet_button: true

# Xing
xing_user: Philipp_Mager6

# Disqus Comments
disqus_short_name: phmager
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-64463047-2

#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap