# Site wide configuration

title:            Phmager
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:year/:month/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Philipp Mager
  avatar: me.png
  bio: "Developer, Enthusiast, Windows Guru"
  email: 
  disqus-shortname: phmager
  twitter: PhilippMager
  google:
    plus: 
    analytics: UA-64463047-2
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: phmager
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: Philipp_Mager6
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
